base_url = "https://4bcx.gitlab.io/no-style-please/"
title = "l0kr blog"
description = "A (nearly) no-CSS, fast, minimalist Zola theme."
theme = "no-style-please"

compile_sass = true
generate_feed = true

taxonomies = [
    { name = "tags" },
    { name = "categories" },
    { name = "contexts" },
]

[markdown]
highlight_code = true

[extra]
author = "Ahmed Alaa"
logo = "images/logo.png"
header_nav = [
    { name = "~home", url = "/" },
    { name = "#tags", url = "/tags" },
    { name = "+categories", url = "/categories" },
    { name = "@contexts", url = "/contexts" },
]
footer_nav = [
    { name = "< previous", url = "#" },
    { name = "webring", url = "#" },
    { name = "next >", url = "#" },
]
